// @ts-nocheck
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async generateMnemonic() : Promise<Result<string, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_mnemonic") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async validateMnemonic(mnemonic: string) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_mnemonic", { mnemonic }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createWallet(mnemonic: string, password: string, accountName: string) : Promise<Result<WalletFile, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_wallet", { mnemonic, password, accountName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importWallet(mnemonic: string, password: string, accountName: string) : Promise<Result<WalletFile, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_wallet", { mnemonic, password, accountName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importPrivateKey(secret: string, password: string, accountName: string) : Promise<Result<WalletFile, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_private_key", { secret, password, accountName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importWalletBackup(walletJson: string, password: string) : Promise<Result<WalletFile, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_wallet_backup", { walletJson, password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unlockWallet(password: string) : Promise<Result<string, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unlock_wallet", { password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async lockWallet() : Promise<void> {
    await TAURI_INVOKE("lock_wallet");
},
async revealMnemonic(password: string) : Promise<Result<string, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reveal_mnemonic", { password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deviceProtectionEnabled() : Promise<boolean> {
    return await TAURI_INVOKE("device_protection_enabled");
},
async enableDeviceProtection(password: string) : Promise<Result<WalletFile, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("enable_device_protection", { password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async disableDeviceProtection(password: string) : Promise<Result<WalletFile, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("disable_device_protection", { password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetLocalWallet() : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_local_wallet") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeWalletPassword(oldPassword: string, newPassword: string) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_wallet_password", { oldPassword, newPassword }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportWalletToPath(password: string, path: string) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_wallet_to_path", { password, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeWalletNetwork(network: string) : Promise<Result<RuntimeConfig, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_wallet_network", { network }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setEnabledNetworks(networks: string[]) : Promise<Result<RuntimeConfig, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_enabled_networks", { networks }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setAccountName(name: string) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_account_name", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listNetworks() : Promise<NetworkInfo[]> {
    return await TAURI_INVOKE("list_networks");
},
async getWalletSnapshot() : Promise<Result<WalletSnapshot, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_wallet_snapshot") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getActivity(limit: number) : Promise<Result<ActivityItem[], ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_activity", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async previewSend(to: string, amount: number, asset: string | null) : Promise<Result<SendPreview, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_send", { to, amount, asset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sendTransfer(password: string, to: string, amount: number, asset: string | null) : Promise<Result<SendResult, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_transfer", { password, to, amount, asset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resolveToken(mint: string) : Promise<Result<TokenInfo, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_token", { mint }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchTokens(query: string) : Promise<Result<TokenInfo[], ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_tokens", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async previewSwapQuote(inputMint: string, outputMint: string, amountUi: number, slippageBps: number) : Promise<Result<SwapQuote, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_swap_quote", { inputMint, outputMint, amountUi, slippageBps }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async executeSwap(password: string, inputMint: string, outputMint: string, amountUi: number, slippageBps: number) : Promise<Result<SwapResult, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("execute_swap", { password, inputMint, outputMint, amountUi, slippageBps }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAppSettings() : Promise<Result<AppSettings, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateAppSettings(settings: AppSettings) : Promise<Result<RuntimeConfig, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_app_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getManagedDefaultRpcUrl(network: string | null) : Promise<string> {
    return await TAURI_INVOKE("get_managed_default_rpc_url", { network });
},
async setOnboardingDraft(draft: OnboardingDraft) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_onboarding_draft", { draft }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getOnboardingDraft() : Promise<Result<OnboardingDraft | null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_onboarding_draft") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearOnboardingDraft() : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_onboarding_draft") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type ActivityItem = { txid: string; timestamp: number | null; status: string; direction: string; amount: number | null; amount_symbol: string | null; description: string }
export type ApiError = { code: string; message: string }
export type AppSettings = { 
/**
 * Optional user override (Advanced). Empty / None = managed default for `network`.
 * Legacy single-URL field; treated as the Solana override when `rpc_urls` has no Solana key.
 */
rpc_url: string | null; 
/**
 * Per-network RPC / Esplora overrides. Keyed by network id.
 */
rpc_urls?: Partial<{ [key in string]: string }>; 
/**
 * Optional Jupiter portal key (Advanced). None = keyless.
 */
jupiter_api_key: string | null; 
/**
 * Active network id. Synced with `WalletFile.network` on switch.
 */
network?: string; 
/**
 * Activated mainnets (Phantom-style). Testnets stay Advanced via `network`.
 */
enabled_networks?: string[]; 
/**
 * Optional 0x API key for Ethereum swaps.
 */
zerox_api_key?: string | null; 
/**
 * Minutes of idle time before auto-lock. Defaults to 5. `0` disables.
 */
auto_lock_minutes?: number | null; 
/**
 * When true, mask balances in the UI. Defaults to hidden.
 */
hide_balances?: boolean; explorer?: ExplorerKind; default_slippage_bps?: number; 
/**
 * Desktop / compact / phone chrome (tracks window size).
 */
app_view?: AppViewKind; 
/**
 * Last window width in logical pixels. Restored on launch when set.
 */
window_width?: number | null; 
/**
 * Last window height in logical pixels. Restored on launch when set.
 */
window_height?: number | null; 
/**
 * User-added Swap tokens (keyword search selections). Instant on reopen.
 */
swap_favorite_tokens?: TokenInfo[] }
/**
 * App chrome layout preference (synced from window size).
 */
export type AppViewKind = "desktop" | "compact" | "phone"
export type ChainFamily = "solana" | "evm" | "bitcoin" | "sui"
export type ChainFeatures = { tokens: boolean; swap: boolean; utxo: boolean }
/**
 * One family's balances inside a multi-chain portfolio.
 */
export type ChainSnapshot = { network: string; public_key: string | null; native_balance: number | null; native_symbol: string; native_price_usd: number | null; native_value_usd: number | null; total_usd: number | null; tokens: TokenBalance[] | null }
export type CryptoEnvelope = { kdf: string; salt: string; cipher: string; nonce: string; ciphertext: string }
export type ExplorerKind = "solscan" | "solanaExplorer"
/**
 * How secrets were imported. Key-only wallets cannot derive other families.
 */
export type ImportKind = "mnemonic" | "solana-key" | "evm-key" | "bitcoin-key" | "sui-key"
/**
 * Specta/UI copy of a descriptor (owned strings).
 */
export type NetworkInfo = { id: string; family: ChainFamily; name: string; native_symbol: string; is_testnet: boolean; eip155_chain_id: number | null; default_rpc: string; explorer_tx: string; explorer_address: string; features: ChainFeatures; enabled: boolean }
export type OnboardingDraft = { mnemonic?: string; mode: string; 
/**
 * Raw private key when `mode` is `import-key`.
 */
secret?: string; import_kind?: string; account_name?: string }
export type RuntimeConfig = { rpc_url: string; jupiter_api_key: string | null }
export type SendPreview = { from: string; to: string; token: string; amount: string; network_name: string; estimated_fee: number; fee_symbol: string; 
/**
 * True when the recipient's associated token account will be created in this transfer.
 */
creates_token_account: boolean }
export type SendResult = { txid: string; status: string }
export type SwapQuote = { input_mint: string; output_mint: string; input_symbol: string; output_symbol: string; in_amount: string; out_amount: string; in_amount_ui: number; out_amount_ui: number; price_impact_pct: number | null; network_fee: number; fee_symbol: string; slippage_bps: number; route?: string }
export type SwapResult = { signature: string; status: string }
export type TokenBalance = { mint: string; symbol: string; name: string; amount: string; decimals: number; ui_amount: number; logo_uri: string | null; price_usd: number | null; value_usd: number | null }
export type TokenInfo = { mint: string; symbol: string; name: string; decimals: number; logo_uri: string | null }
/**
 * Public addresses keyed by family. Secrets are never stored here.
 */
export type WalletAddresses = { solana?: string | null; evm?: string | null; bitcoin?: string | null; sui?: string | null }
export type WalletFile = { version: number; wallet_id: string; network: string; public_key: string; created_at: string; 
/**
 * Absent in older files → password-only.
 */
protection?: WalletProtection; 
/**
 * Public family addresses. Missing on v1 files.
 */
addresses?: WalletAddresses; account_name?: string; import_kind?: ImportKind; enabled_networks?: string[]; crypto: CryptoEnvelope }
/**
 * How the wallet ciphertext is keyed.
 */
export type WalletProtection = 
/**
 * Argon2id(password) only — portable with JSON + password.
 */
"password" | 
/**
 * Argon2id(password) + OS keychain device secret — not portable off-device.
 */
"password-device"
export type WalletSnapshot = { exists: boolean; unlocked: boolean; 
/**
 * Last-used network for Send / Receive (not an exclusive mode).
 */
network: string; 
/**
 * Last-used chain receive address (public).
 */
public_key: string | null; native_balance: number | null; native_symbol: string; native_price_usd: number | null; native_value_usd: number | null; total_portfolio_usd: number | null; tokens: TokenBalance[] | null; chains?: ChainSnapshot[]; account_name?: string; import_kind?: ImportKind; enabled_networks?: string[]; can_reveal_mnemonic?: boolean }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
