// @ts-nocheck
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async generateMnemonic() : Promise<Result<string, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_mnemonic") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async validateMnemonic(mnemonic: string) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_mnemonic", { mnemonic }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createWallet(mnemonic: string, password: string) : Promise<Result<WalletFile, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_wallet", { mnemonic, password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importWallet(mnemonic: string, password: string) : Promise<Result<WalletFile, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_wallet", { mnemonic, password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unlockWallet(password: string) : Promise<Result<string, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unlock_wallet", { password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async lockWallet() : Promise<void> {
    await TAURI_INVOKE("lock_wallet");
},
async revealMnemonic() : Promise<Result<string, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reveal_mnemonic") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeWallet(password: string) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_wallet", { password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeWalletPassword(oldPassword: string, newPassword: string) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_wallet_password", { oldPassword, newPassword }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportWallet(password: string) : Promise<Result<string, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_wallet", { password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportWalletToPath(password: string, path: string) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_wallet_to_path", { password, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeWalletNetwork(network: Network) : Promise<Result<RuntimeConfig, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_wallet_network", { network }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWalletSnapshot() : Promise<Result<WalletSnapshot, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_wallet_snapshot") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSolBalance() : Promise<Result<number, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_sol_balance") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTokenBalances() : Promise<Result<TokenBalance[], ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_token_balances") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getActivity(limit: number) : Promise<Result<ActivityItem[], ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_activity", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async previewSolSend(to: string, amountSol: number) : Promise<Result<SendPreview, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_sol_send", { to, amountSol }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async previewSplSend(mint: string, to: string, amount: number) : Promise<Result<SendPreview, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_spl_send", { mint, to, amount }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sendSol(password: string, to: string, amountSol: number) : Promise<Result<SendResult, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_sol", { password, to, amountSol }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sendSpl(password: string, mint: string, to: string, amount: number) : Promise<Result<SendResult, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_spl", { password, mint, to, amount }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resolveToken(mint: string) : Promise<Result<TokenInfo, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_token", { mint }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchTokens(query: string) : Promise<Result<TokenInfo[], ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_tokens", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async previewSwapQuote(inputMint: string, outputMint: string, amountUi: number, slippageBps: number) : Promise<Result<SwapQuote, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_swap_quote", { inputMint, outputMint, amountUi, slippageBps }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async executeSwap(password: string, inputMint: string, outputMint: string, amountUi: number, slippageBps: number) : Promise<Result<SwapResult, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("execute_swap", { password, inputMint, outputMint, amountUi, slippageBps }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAppSettings() : Promise<Result<AppSettings, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateAppSettings(settings: AppSettings) : Promise<Result<RuntimeConfig, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_app_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getManagedDefaultRpcUrl(network: Network | null) : Promise<string> {
    return await TAURI_INVOKE("get_managed_default_rpc_url", { network });
},
async setOnboardingDraft(mnemonic: string, mode: string) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_onboarding_draft", { mnemonic, mode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getOnboardingDraft() : Promise<Result<OnboardingDraft | null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_onboarding_draft") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearOnboardingDraft() : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_onboarding_draft") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type ActivityItem = { signature: string; timestamp: number | null; status: string; direction: string; amount_sol: number | null; description: string }
export type ApiError = { code: string; message: string }
export type AppSettings = { 
/**
 * Optional user override (Advanced). Empty / None = managed default for `network`.
 */
rpc_url: string | null; 
/**
 * Optional Jupiter portal key (Advanced). None = keyless.
 */
jupiter_api_key: string | null; 
/**
 * Active Solana cluster. Synced with `WalletFile.network` on switch.
 */
network?: Network; 
/**
 * Minutes of idle time before auto-lock. Defaults to 5. `0` disables.
 */
auto_lock_minutes?: number | null; 
/**
 * When true, mask balances in the UI. Defaults to hidden.
 */
hide_balances?: boolean; explorer?: ExplorerKind; default_slippage_bps?: number; 
/**
 * Desktop / compact / phone chrome (tracks window size).
 */
app_view?: AppViewKind; 
/**
 * Last window width in logical pixels. Restored on launch when set.
 */
window_width?: number | null; 
/**
 * Last window height in logical pixels. Restored on launch when set.
 */
window_height?: number | null; 
/**
 * User-added Swap tokens (keyword search selections). Instant on reopen.
 */
swap_favorite_tokens?: TokenInfo[] }
/**
 * App chrome layout preference (synced from window size).
 */
export type AppViewKind = "desktop" | "compact" | "phone"
export type CryptoEnvelope = { kdf: string; salt: string; cipher: string; nonce: string; ciphertext: string }
export type ExplorerKind = "solscan" | "solanaExplorer"
export type Network = "solana-mainnet" | "solana-devnet"
export type OnboardingDraft = { mnemonic: string; mode: string }
export type RuntimeConfig = { rpc_url: string; jupiter_api_key: string | null }
export type SendPreview = { from: string; to: string; token: string; amount: string; estimated_fee_lamports: number; estimated_fee_sol: number; 
/**
 * True when the recipient's associated token account will be created in this transfer.
 */
creates_token_account: boolean }
export type SendResult = { signature: string; status: string }
export type SwapQuote = { input_mint: string; output_mint: string; input_symbol: string; output_symbol: string; in_amount: string; out_amount: string; in_amount_ui: number; out_amount_ui: number; price_impact_pct: number | null; network_fee_lamports: number; network_fee_sol: number; slippage_bps: number }
export type SwapResult = { signature: string; status: string }
export type TokenBalance = { mint: string; symbol: string; name: string; amount: string; decimals: number; ui_amount: number; logo_uri: string | null; price_usd: number | null; value_usd: number | null }
export type TokenInfo = { mint: string; symbol: string; name: string; decimals: number; logo_uri: string | null }
export type WalletFile = { version: number; wallet_id: string; network: string; public_key: string; created_at: string; crypto: CryptoEnvelope }
export type WalletSnapshot = { exists: boolean; unlocked: boolean; 
/**
 * Wallet file network id (e.g. `solana-mainnet`). Empty wallet → default mainnet.
 */
network: string; public_key: string | null; sol_balance: number | null; sol_price_usd: number | null; sol_value_usd: number | null; total_portfolio_usd: number | null; tokens: TokenBalance[] | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
