// @ts-nocheck
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async walletExists() : Promise<boolean> {
    return await TAURI_INVOKE("wallet_exists");
},
async generateMnemonic() : Promise<Result<string, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_mnemonic") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createWallet(mnemonic: string, password: string) : Promise<Result<WalletFile, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_wallet", { mnemonic, password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importWallet(mnemonic: string, password: string) : Promise<Result<WalletFile, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_wallet", { mnemonic, password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unlockWallet(password: string) : Promise<Result<string, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unlock_wallet", { password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async lockWallet() : Promise<void> {
    await TAURI_INVOKE("lock_wallet");
},
async isUnlocked() : Promise<boolean> {
    return await TAURI_INVOKE("is_unlocked");
},
async getPublicKey() : Promise<string | null> {
    return await TAURI_INVOKE("get_public_key");
},
async revealMnemonic(password: string) : Promise<Result<string, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reveal_mnemonic", { password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWalletSnapshot() : Promise<Result<WalletSnapshot, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_wallet_snapshot") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSolBalance() : Promise<Result<number, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_sol_balance") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTokenBalances() : Promise<Result<TokenBalance[], ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_token_balances") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getActivity(limit: number) : Promise<Result<ActivityItem[], ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_activity", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async previewSolSend(to: string, amountSol: number) : Promise<Result<SendPreview, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_sol_send", { to, amountSol }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async previewSplSend(mint: string, to: string, amount: number) : Promise<Result<SendPreview, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_spl_send", { mint, to, amount }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sendSol(password: string, to: string, amountSol: number) : Promise<Result<SendResult, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_sol", { password, to, amountSol }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sendSpl(password: string, mint: string, to: string, amount: number) : Promise<Result<SendResult, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_spl", { password, mint, to, amount }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type ActivityItem = { signature: string; timestamp: number | null; status: string; direction: string; amount_sol: number | null; description: string }
export type ApiError = { code: string; message: string }
export type CryptoEnvelope = { kdf: string; salt: string; cipher: string; nonce: string; ciphertext: string }
export type SendPreview = { from: string; to: string; token: string; amount: string; estimated_fee_lamports: number; estimated_fee_sol: number }
export type SendResult = { signature: string; status: string }
export type TokenBalance = { mint: string; symbol: string; name: string; amount: string; decimals: number; ui_amount: number }
export type WalletFile = { version: number; wallet_id: string; network: string; public_key: string; created_at: string; crypto: CryptoEnvelope }
export type WalletSnapshot = { exists: boolean; unlocked: boolean; public_key: string | null; sol_balance: number | null; tokens: TokenBalance[] | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
