[package]
name = "taurvia-evm"
version = "0.5.2"
edition.workspace = true
license.workspace = true

[dependencies]
models = { path = "../models" }
taurvia-chain = { path = "../taurvia-chain" }
anyhow.workspace = true
bip32.workspace = true
hex.workspace = true
k256.workspace = true
sha3.workspace = true
zeroize.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
futures.workspace = true
alloy = { version = "1.0.38", default-features = false, features = [
    "std",
    "provider-http",
    "rpc-types",
    "signer-local",
    "consensus",
    "network",
    "sol-types",
    "contract",
    "reqwest",
    "reqwest-rustls-tls",
] }

[dev-dependencies]
taurvia-hd = { path = "../taurvia-hd" }
